### ISSUE TITLE
CronExpression Class

### ISSUE THREAD

**Issue by lonnieezell** [lonnieezell/codeigniter4-tasks#1]
The CronExpression class should be able to:

- understand the standard cron format (* * * * *)
- be able to check if a task should be ran based on the cron expression and the current time
- should be able to run based upon a different timezone than the current system settings
- should be able to list future and previous run times.

**Comment by colethorsen** [comment]
Does it make sense to reinvent this, or would using something like: https://github.com/dragonmantank/cron-expression be acceptable? It's probably slightly more complex than necessary, but given that the use case for this is running via the console and cron task it wouldn't really add overhead for a real user.

The cronexpression started here works really well for determining if a task should run right now or on a set date, but thats the easy part the next/previous run requirement gets much more complex.

**Comment by lonnieezell** [comment]
Next run date has been implemented now. Last run will be determined by the last time it _actually_ ran. Just need to decide how to store that.

**Comment by MGatner** [comment]
I'm in favor of a database table of all runs with some sort of status or result. This could have a Config property for "keep the last x days of history" to keep it under control.
