### ISSUE TITLE
codeigniter4/tasks missing in packagists

### ISSUE THREAD

**Issue by sammyskills** [lonnieezell/codeigniter4-tasks#149]
I tried to use this library using `composer require codeigniter4/tasks` just like the docs say, but it returned the error below:

```console
./composer.json has been updated
Running composer update codeigniter4/tasks
Loading composer repositories with package information
Updating dependencies
Your requirements could not be resolved to an installable set of packages.

  Problem 1
    - Root composer.json requires codeigniter4/tasks, it could not be found in any version, there may be a typo in the package name.

Potential causes:
 - A typo in the package name
 - The package is not available in a stable-enough version according to your minimum-stability setting
   see <https://getcomposer.org/doc/04-schema.md#minimum-stability> for more details.
 - It's a private package and you forgot to add a custom repository to find it  

Read <https://getcomposer.org/doc/articles/troubleshooting.md> for further common problems.

Installation failed, reverting ./composer.json and ./composer.lock to their original content.
```
Upon troubleshooting, I realised that the package doesn't exist in packagist.org:

![image](https://github.com/codeigniter4/tasks/assets/8720569/fe9aa1ba-3d5a-4c97-8ec9-a6fb5edc9083)

Is this an oversight?

**Comment by lonnieezell** [comment]
Yup- it's an oversight. Thank you for pointing it out! 

It's been added to Packagist now. Let us know if you still have any problems with it.

**Comment by sammyskills** [comment]
Great.  It works now. 

I think it should also be pointed out in the installation docs that the `dev:develop` tag/flag has to be added pending when an official version is released.
