### ISSUE TITLE
why are there no tagged releases

### ISSUE THREAD

**Issue by twinklebob** [lonnieezell/codeigniter4-tasks#166]
I can't install using `composer` as there are no tagged releases and there's not a chance in hell I'm putting "dev-develop" into production as there's no guarantee that every server involved will pull down the same version of the code. Is there a particular reason that there are no tagged releases that composer can make use of?

**Comment by kenjis** [comment]
Because it is not yet released.
You can install the exact same version with `composer.lock`.
Learn how `composer` works.
