### ISSUE TITLE
Callables

### ISSUE THREAD

**Issue by MGatner** [lonnieezell/codeigniter4-tasks#36]
I wonder about the choice to use `Closure` for the "on-the-fly" task type. It seems unnecessarily restrictive over `callable`, however when I went to expand it this is the prohibitive piece:
```
        // Get a hash based on the action
        // Closures cannot be serialized so do it the hard way
        if ($this->getType() === 'closure') {
            $ref  = new \ReflectionFunction($this->getAction());
            $file = new \SplFileObject($ref->getFileName());
            $file->seek($ref->getStartLine() - 1);
            $content = '';

            while ($file->key() < $ref->getEndLine()) {
                $content .= $file->current();
                $file->next();
            }
            $actionString = json_encode([
                $content,
                $ref->getStaticVariables(),
            ]);
```

I assume this is just a convenient way of identifying the task - could we come up with a way to expand this to handle all `callable` type?

**Comment by lonnieezell** [comment]
Yes, that's a way to provide a "uniqued" id for the callable. 

However, I don't find closures to be all that restrictive since you can use about any callable you need from inside the closure.

**Comment by MGatner** [comment]
You can, but since I haven't wanted my tasks to be available to **spark** I've been writing them in separate classes, so wrapping it in a Closure feels silly:
```
$schedule->call(static function() { 
            MyTask::run();
        })->everyMonday();
```

For now I've decided to move them to Commands since it will help with the development.

**Comment by lonnieezell** [comment]
I've found in my day job that having those as commands is quite often a life-saver since the client or QA team wants it run "right now!" and can't wait for it to run naturally. :) Plus testing it manually during development is simpler.
